import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {fileURLToPath} from 'node:url';
import {mkdtempSync,rmSync,readFileSync,cpSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:net';
import {once} from 'node:events';
import {foundry} from 'viem/chains';
import {createWalletClient,http} from 'viem';
import {mnemonicToAccount} from 'viem/accounts';
import {startAuditServer} from '../../src/demo/audit-server.js';
import {Operator} from '../../src/operator/run.js';
import {canonical} from '../../src/v3/crypto.js';

test('automatic operator handles three requests, replay and process restart without duplicate batches', {timeout:60000}, async t=>{
 const socket=createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
 const rpcUrl=`http://127.0.0.1:${port}`,anvil=spawn('anvil',['--port',String(port),'--silent'],{stdio:'ignore'});
 const dir=mkdtempSync(join(tmpdir(),'trust404-op-'));let op;
 t.after(()=>{op?.close();anvil.kill();rmSync(dir,{recursive:true,force:true});});
 const config={rpcUrl,chain:foundry,token:'0x0000000000000000000000000000000000000001'};
 op=new Operator(dir,config);const identity=op.init();
 for(let i=0;i<50;i++){try{await op.client.getBlockNumber();break;}catch{await new Promise(r=>setTimeout(r,100));}}
 await op.client.request({method:'anvil_setBalance',params:[identity.address,'0xde0b6b3a7640000']});
 const account=mnemonicToAccount('test test test test test test test test test test test junk');const wallet=createWalletClient({account,chain:foundry,transport:http(rpcUrl)});
 const token=JSON.parse(readFileSync('out/RecordAnchor.t.sol/TestToken.json'));
 const receipt=await op.client.waitForTransactionReceipt({hash:await wallet.deployContract({abi:token.abi,bytecode:token.bytecode.object})});config.token=receipt.contractAddress.toLowerCase();
 await op.deploy();op.open();
 for(let i=1;i<=2;i++)op.request('50000000',`request${i}`);
 await op.submit('50000000','request3');
 const result=op.load('audit-result.json');assert.equal(result.ok,true);assert.equal(result.requests.length,3);assert.equal(result.batchCount,'2');
 assert(result.requests.every(r=>r.decisions[0].outcome==='REJECTED'));
 op.close();op=new Operator(dir,config);op.init();op.open();
 assert.equal(op.request('50000000','request1').duplicate,true);
 assert.throws(()=>op.request('60000000','request1'),/IDEMPOTENCY_CONFLICT/);
 const repeated=await op.cycle();assert.equal(repeated.batchCount,'2');assert.equal(repeated.ok,true);
 const completed=await op.submit('50000000','request1');
 assert.equal(completed.status,'RECORDED');assert.equal(completed.auditOk,true);
 const server=await startAuditServer(completed.profilesFile,0);
 t.after(()=>server.close());
 const base=`http://127.0.0.1:${server.address().port}`;
 const upload=JSON.parse(readFileSync(completed.auditFile));
 // The auditor only receives exported public files, never the operator DB or keys.
 const post=async data=>{const response=await fetch(base+'/api/audit-file',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});assert.equal(response.status,200);return response.json();};
 assert.equal((await post(upload)).ok,true);
 assert.deepEqual(await (await fetch(base+'/api/samples')).json(),[]);
 assert.equal((await fetch(base+'/api/profiles')).status,200);
 const missing=structuredClone(upload);delete missing.batches['2'];
 const missingResult=await post(missing);assert.equal(missingResult.ok,false);assert(missingResult.issues.some(i=>i.code==='DATA_UNAVAILABLE'));
 const tampered=structuredClone(upload);tampered.batches['2'][0].decision.payload.reason='FORGED';
 assert.equal((await post(tampered)).ok,false);
 const unknown=structuredClone(upload);unknown.profileId='attacker-profile';
 assert.equal((await fetch(base+'/api/audit-file',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(unknown)})).status,400);
 const journal=op.load('tx-batch-2.json');const count=await op.client.getTransactionCount({address:identity.address});
 await op.transact('batch-2',{to:journal.to,data:journal.data});assert.equal(await op.client.getTransactionCount({address:identity.address}),count);
 // Move only public exports to another working directory; CLI resolves the trust
 // file relative to the config and honors its pinned block, not the current cwd.
 const received=mkdtempSync(join(tmpdir(),'trust404-received-'));
 t.after(()=>rmSync(received,{recursive:true,force:true}));
 cpSync(completed.exportDirectory,received,{recursive:true});
 op.close();op=null;
 const cli=fileURLToPath(new URL('../../src/v3/cli.js',import.meta.url));
 const args=[cli,'verify','verify-config.json','evidence.json'];
 const run=()=>promisify(execFile)(process.execPath,args,{cwd:received,timeout:10000});
 const verified=JSON.parse((await run()).stdout);
 assert.equal(verified.ok,true);assert.equal(verified.outcome,'REJECTED');
 const verifyConfig=JSON.parse(readFileSync(join(received,'verify-config.json')));
 assert.equal(verified.asOf.blockHash,verifyConfig.asOf);
 const evidence=JSON.parse(readFileSync(join(received,'evidence.json')));
 evidence.decision.record.decision.payload.reason='FORGED';
 writeFileSync(join(received,'evidence.json'),canonical(evidence));
 await assert.rejects(run(),error=>error.code===1&&/INVALID_INCLUSION/.test(error.stderr));
});
